agent:
  name: "B-Harvest"
  # host: "cosmos-rpc.polkachu.com"
  host: "135.125.188.77"
  # port: 443
  port: 8545
  # monitors:
  #   - name: blockNumber
  #     interval: 10s # 여기서 interval을 지정해 줍니다.
  pushInterval: 10s
  timeout: 10s
  commitId: 19ge4rgndfifji
database:
  user: test
  password: test
  host: 127.0.0.1
  port: 33306
  dbName: harvestmon
