commitId = "helloworld"
agentName = "local"

[tendermint.default]
host = "localhost"
port = 26657

[[tendermint.default.collectors]]
name = "tm:status"
interval = "1s"

[[tendermint.default.collectors]]
name = "tm:commit"

[[tendermint.default.collectors]]
name = "tm:net_info"

[ethereum.default]
host = "eth.llamarpc.com"
port = 443

[[ethereum.default.collectors]]
name = "eth:block_number"

[node.default]
host = "localhost"
port = 59100
interval = "3s"

[[node.default.collectors]]
name = "node:cpu"

[[node.default.collectors]]
name = "node:memory"

[[node.default.collectors]]
name = "node:network"

[[node.default.collectors]]
name = "node:disk"

[[node.default.collectors]]
name = "node:systemd"

[database]
user = "root"
password = "test"
host = "localhost"
port = "33306"
dbName = "test"

[http]
[http.transport]
maxConnsPerHost = 3